// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi01mU8FSdwjktLrQd1kgMxXsR2W2P3Bw',
    appId: '1:94452679667:web:6cbb4609adb171cfa3c886',
    messagingSenderId: '94452679667',
    projectId: 'helpdeskapp-f73d2',
    authDomain: 'helpdeskapp-f73d2.firebaseapp.com',
    storageBucket: 'helpdeskapp-f73d2.firebasestorage.app',
    measurementId: 'G-9D066B3X8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDd2UdK_jzhO04_LdLBIUpz8rzwlF0ZTo',
    appId: '1:94452679667:android:158d5247162a8315a3c886',
    messagingSenderId: '94452679667',
    projectId: 'helpdeskapp-f73d2',
    storageBucket: 'helpdeskapp-f73d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjyF8giPvoYaJplojlc7vLKA6IFvaMf2c',
    appId: '1:94452679667:ios:3c27c47098aaab37a3c886',
    messagingSenderId: '94452679667',
    projectId: 'helpdeskapp-f73d2',
    storageBucket: 'helpdeskapp-f73d2.firebasestorage.app',
    iosBundleId: 'com.shinobidev.helpDesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjyF8giPvoYaJplojlc7vLKA6IFvaMf2c',
    appId: '1:94452679667:ios:3c27c47098aaab37a3c886',
    messagingSenderId: '94452679667',
    projectId: 'helpdeskapp-f73d2',
    storageBucket: 'helpdeskapp-f73d2.firebasestorage.app',
    iosBundleId: 'com.shinobidev.helpDesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi01mU8FSdwjktLrQd1kgMxXsR2W2P3Bw',
    appId: '1:94452679667:web:e699a4811c32b6d2a3c886',
    messagingSenderId: '94452679667',
    projectId: 'helpdeskapp-f73d2',
    authDomain: 'helpdeskapp-f73d2.firebaseapp.com',
    storageBucket: 'helpdeskapp-f73d2.firebasestorage.app',
    measurementId: 'G-2DKNVBYNGF',
  );

}